version: '3.8'

services:
#  frontend:
#    build:
#      context: ./frontend
#      target: build-stage
#    volumes:
#      - ./frontend:/app
#      #- frontend_dist:/app/dist
#    container_name: frontend-builder
#    # command: tail -f /dev/null
#    command: npm run dev

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
    expose:
      - "9000"
    depends_on:
      - postgres
    container_name: laravel-backend-api

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
#      - frontend
      - backend
    volumes:
#      - frontend_dist:/usr/share/nginx/html:ro
      - ./backend:/var/www
    container_name: nginx-server

volumes:
  #frontend_dist:
  pg_data:


# docker compose build
# docker compose down -v
# docker compose up -d
